# Generated by Django 4.1.6 on 2023-03-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="author_user_id",
            field=models.IntegerField(),
        ),
    ]
