# Generated by Django 4.1.6 on 2023-03-09 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_comment_issue_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="issue_id",
            new_name="issue",
        ),
    ]
