# Generated by Django 4.1.6 on 2023-03-23 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0004_rename_author_user_id_contributors_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_user_id",
                to="web.projects",
            ),
        ),
        migrations.AlterField(
            model_name="contributors",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_contributer_user_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
