# Generated by Django 4.1.6 on 2023-03-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0005_alter_contributors_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.projects"
            ),
        ),
        migrations.AlterField(
            model_name="contributors",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
