# Generated by Django 4.1.6 on 2023-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_contributors_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="project_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="contributors",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
