# Generated by Django 4.1.6 on 2023-04-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_comment_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_issue",
                to="web.issue",
            ),
        ),
    ]
