# Generated by Django 4.1.6 on 2023-05-19 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_alter_contributors_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contribiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
