# Generated by Django 4.1.6 on 2023-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_issue_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributors',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_draft_user'),
        ),
    ]
